FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY receive.py requirements.txt ./

RUN pip install -r requirements.txt
