services:
  idle:
    image: python:3.8
    command: sleep infinity
    container_name: idle
    networks:
      - nw

networks:
  nw:
    name: br0
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
      
