services:
  attacker:
    #image: python:3.8
    #image: alpine
    #command: sleep infinity
    build: 
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attack
    networks:
      nw2:
        ipv4_address: 172.21.0.2
    depends_on:
      - idle
      - victim
  idle: 
    image: alpine
    command: sleep infinity
    container_name: idle
    ports:
      - "8080:8080"
    networks:
      nw:
        ipv4_address: 172.20.0.3
  victim:
    image: alpine
    command: sleep infinity
    container_name: victim
    ports:
      - "8081:8081"
    networks:
      nw:
        ipv4_address: 172.20.0.4
  monitor:
    build: 
      context: .
      dockerfile: Dockerfile.monitor
    container_name: monitor
    networks:
      nw:
        ipv4_address: 172.20.0.5

networks:
  nw:
    name: br0
    driver_opts:
      com.docker.network.bridge.name: br0
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0

    ipam:
      config:
        - subnet: 172.20.0.0/16
  nw2:
    name: br1
    driver_opts:
      com.docker.network.bridge.name: br1
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
    ipam:
      config:
        - subnet: 172.21.0.0/16
  
      
