services:
  send:
    container_name: send
    image: python:3.8
    build: 
      context: ./send
      dockerfile: Dockerfile.send
    command: cat main.py
    ports:
      - 8000:8000
    networks:
      nw:
        ipv4_address: 172.20.0.2

  receive:
    container_name: receive
    image: python:3.8
    build: 
      context: ./receive
      dockerfile: Dockerfile.receive
    command: ls -a
    ports:
      - 8001:8001
    networks:
      nw:
        ipv4_address: 172.20.0.3


networks:
  nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br0