services:
  send:

    build: 
      context: ./send
    command: ls -a
    ports:
      - 8000:8000

    container_name: send
    networks:
      nw:
        ipv4_address: 172.20.0.2

  receive:

    build: 
      context: ./receive
    command: ls -a
    ports:
      - 8001:8001
    container_name: receive
    networks:
      nw:
        ipv4_address: 172.20.0.3


networks:
  nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
