services:
  send:
    build:
      context: .
    command: python send.py
    ports:
      - 8000:8000
    container_name: send
    networks:
      nw:
        ipv4_address: 172.20.0.2

networks:
  nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
